defmodule AdventOfCode.Day06Test do
  use ExUnit.Case

  test "part1" do
    input = """
    ....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...
    """

    assert AdventOfCode.Day06.part1(input) == 41
  end

  test "part2" do
    input = """
    ....#.....
    .........#
    ..........
    ..#.......
    .......#..
    ..........
    .#..^.....
    ........#.
    #.........
    ......#...
    """

    assert AdventOfCode.Day06.part2(input) == 6
  end
end
